fixtures:
  repositories:
    firewall:
      repo: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: '0.2.1'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    mysql:
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: '3.6.0'
    passenger:
      repo: 'git://github.com/Phil-Friderici/puppetlabs-passenger.git'
      ref: '0.5.0-beta'
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.6.0'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '2.0.1'
    common:
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref: '1.3.0'
    htpasswd:
      repo: 'git://github.com/leinaddm/puppet-htpasswd.git'
  symlinks:
    puppet: "#{source_dir}"
