name    'ghoneycutt-puppet'
version '0.3.0'
source 'UNKNOWN'
author 'puppetlabs'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.2.x'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/passenger', '>= 0.0.4'
dependency 'puppetlabs/apache', '>= 0.5.0'
dependency 'puppetlabs/firewall', '>= 0.2.1'
